### ISSUE TITLE
Tab sorting doesn't work, if tabs use default title

### ISSUE THREAD

**Issue by wesleybl** [eea/volto-tabs-block#33]
If the title of the tabs are the default titles (Tab 1, Tab 2 ...), the sorting of the tabs does not work:

![ordenacao](https://user-images.githubusercontent.com/3297795/214142210-2c2512da-272d-445d-85b4-dc305f178353.gif)

**Comment by tiberiuichim** [comment]
@wesleybl It works, but the widget is misleading.

The widget will automatically create titles for its options, so these titles are automatically generated. Of course they'll renumber once dropped.
